# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 485dad15cb4f33d9e3813050b52dc82e932bd02d1c446bf1b26f290e29c5f8c707b10e09c74b66ea02f03c38fd48d7a38b4149dc93387d60a9f928e1ec5b08e5

test:
  secret_key_base: 331e46234820d902ac1424ec060fa4b1c31789a68160077998ebf97eddd867b013c0e38019c49666fac1e2c4d3d85122a40f5ddf2f62378394aa52bc87e1a7f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
